/-
  RLA — Weyl Geometry Connection
  Pinnacle Quantum Group — April 2026

  Proves the Weyl geometry interpretation: α is a Weyl 1-form
  inducing non-metricity ∇̃_ρ g_{μν} = -2α_ρ g_{μν}.
  When α = 0, the Weyl connection reduces to Levi-Civita.
  When α = dσ is exact, the gauge transform g → e^{-2σ}g eliminates it:
  this is proved with real derivatives (`deriv`/`HasDerivAt`) on a 1-D
  chart, where the derivative of the conformal factor e^{-2σ} cancels
  exactly the α-term of the non-metricity equation.
  Reference: RLA README §9, Appendix F
-/
import Mathlib

noncomputable section
open Real

namespace RLA.WeylGeometry

/-! ## 1. Weyl Connection Model (1D scalar model for key properties) -/

structure WeylConnection where
  christoffel : ℝ
  alpha : ℝ

def weylModifiedChristoffel (Γ α : ℝ) : ℝ := Γ + 2 * α

/-! ## 2. Non-Metricity: ∇̃g = -2αg -/

def nonMetricity (α g : ℝ) : ℝ := -2 * α * g

theorem nonmetricity_vanishes_iff (α g : ℝ) (hg : g ≠ 0) :
    nonMetricity α g = 0 ↔ α = 0 := by
  unfold nonMetricity
  constructor
  · intro h
    have h1 : α * g = 0 := by linarith
    exact (mul_eq_zero.mp h1).resolve_right hg
  · intro h; rw [h]; ring

/-! ## 3. α = 0 Recovers Levi-Civita -/

theorem levi_civita_recovery (Γ : ℝ) :
    weylModifiedChristoffel Γ 0 = Γ := by
  unfold weylModifiedChristoffel; ring

theorem zero_alpha_metricity (g : ℝ) :
    nonMetricity 0 g = 0 := by
  unfold nonMetricity; ring

/-! ## 4. Exact α Gauge Elimination
    When α = dσ, the gauge transform g → e^{-2σ}g sets α → 0.

    This is proved with real derivatives on a 1-D chart: the metric is a
    function `g : ℝ → ℝ`, the Weyl form is `α : ℝ → ℝ`, and exactness means
    `α = deriv σ`.  With the Weyl coefficient `Γ̃ = Γ + 2α` of §1 acting on
    both lower indices of `g` (flat chart, `Γ = 0`), the non-metricity
    equation `∇̃g = -2αg` of §2 is the ODE `deriv g = 2αg`
    (`satisfiesNonMetricity_iff`).  The gauge transform shifts the Weyl form
    by `-dσ` (`gauge_covariance`), so an exact `α = dσ` is eliminated and
    metric compatibility is restored (`exact_alpha_eliminated`,
    `gauge_recovers_metric_compatibility`).  An earlier version of this
    section rendered exactness as an equation `α = σ` between two real
    numbers, which made elimination the tautology `α - σ = 0`; the statements
    below carry the actual derivative content. -/

def gaugeTransform (g σ : ℝ) : ℝ := exp (-2 * σ) * g

theorem gauge_preserves_positivity (g σ : ℝ) (hg : 0 < g) :
    0 < gaugeTransform g σ := by
  unfold gaugeTransform
  exact mul_pos (exp_pos _) hg

/-- Weyl covariant derivative of the metric function `g` on a 1-D chart:
    each of the two lower indices of `g` contributes `-Γ̃ g`, where
    `Γ̃ = weylModifiedChristoffel Γ (α x)` is the coefficient from §1. -/
def weylCovDeriv (Γ : ℝ) (α g : ℝ → ℝ) (x : ℝ) : ℝ :=
  deriv g x - 2 * weylModifiedChristoffel Γ (α x) * g x

/-- The Weyl non-metricity equation `∇̃g = -2αg` on the flat chart (`Γ = 0`),
    stated with `weylCovDeriv` and the `nonMetricity` of §2. -/
def SatisfiesNonMetricity (α g : ℝ → ℝ) : Prop :=
  ∀ x, weylCovDeriv 0 α g x = nonMetricity (α x) (g x)

/-- On the flat chart the non-metricity equation is the ODE `∂g = 2αg`. -/
theorem satisfiesNonMetricity_iff (α g : ℝ → ℝ) :
    SatisfiesNonMetricity α g ↔ ∀ x, deriv g x = 2 * α x * g x := by
  unfold SatisfiesNonMetricity weylCovDeriv weylModifiedChristoffel nonMetricity
  constructor <;> intro h x <;> linarith [h x]

/-- Under the gauge transform generated by `σ`, the Weyl form shifts by the
    exact form `-dσ`: on the 1-D chart, `α ↦ α - deriv σ`. -/
def transformedAlpha (α σ : ℝ → ℝ) (x : ℝ) : ℝ := α x - deriv σ x

/-- When `α = dσ` is exact, the transformed Weyl form vanishes identically. -/
theorem transformedAlpha_exact (σ : ℝ → ℝ) :
    transformedAlpha (deriv σ) σ = fun _ => 0 := by
  funext x
  simp [transformedAlpha]

/-- Derivative of the gauge-transformed metric `x ↦ e^{-2σ(x)} g(x)`: the
    conformal factor contributes exactly the extra term `-2 (dσ) ĝ`. -/
theorem gaugeTransform_hasDerivAt (σ g : ℝ → ℝ) (x : ℝ)
    (hσ : DifferentiableAt ℝ σ x) (hg : DifferentiableAt ℝ g x) :
    HasDerivAt (fun y => gaugeTransform (g y) (σ y))
      (-2 * deriv σ x * gaugeTransform (g x) (σ x) + exp (-2 * σ x) * deriv g x)
      x := by
  have hexp : HasDerivAt (fun y => exp (-2 * σ y))
      (exp (-2 * σ x) * (-2 * deriv σ x)) x :=
    (hσ.hasDerivAt.const_mul (-2 : ℝ)).exp
  have h := hexp.mul hg.hasDerivAt
  have hval : -2 * deriv σ x * gaugeTransform (g x) (σ x) + exp (-2 * σ x) * deriv g x
      = exp (-2 * σ x) * (-2 * deriv σ x) * g x + exp (-2 * σ x) * deriv g x := by
    unfold gaugeTransform; ring
  rw [hval]
  exact h

/-- Flat-chart derivative of the gauge-transformed metric:
    `∂ĝ = -2 (dσ) ĝ + e^{-2σ} ∂g`. -/
theorem gaugeTransform_deriv (σ g : ℝ → ℝ) (x : ℝ)
    (hσ : DifferentiableAt ℝ σ x) (hg : DifferentiableAt ℝ g x) :
    deriv (fun y => gaugeTransform (g y) (σ y)) x
      = -2 * deriv σ x * gaugeTransform (g x) (σ x) + exp (-2 * σ x) * deriv g x :=
  (gaugeTransform_hasDerivAt σ g x hσ hg).deriv

/-- Pointwise gauge covariance of the non-metricity equation: a solution for
    the Weyl form `α` transforms into a solution for
    `transformedAlpha α σ = α - dσ`. -/
theorem gauge_transforms_alpha (α σ g : ℝ → ℝ) (x : ℝ)
    (hσ : DifferentiableAt ℝ σ x) (hg : DifferentiableAt ℝ g x)
    (h_weyl : deriv g x = 2 * α x * g x) :
    deriv (fun y => gaugeTransform (g y) (σ y)) x
      = 2 * transformedAlpha α σ x * gaugeTransform (g x) (σ x) := by
  rw [gaugeTransform_deriv σ g x hσ hg, h_weyl]
  unfold transformedAlpha gaugeTransform
  ring

/-- **Exact α elimination, with real derivatives.**  If `α = dσ` is exact and
    `g` solves the non-metricity ODE `∂g = 2αg`, then the gauge-transformed
    metric `ĝ = e^{-2σ} g` has vanishing derivative: the α-term is cancelled
    by the derivative of the conformal factor, not by substituting a
    hypothesis. -/
theorem exact_alpha_eliminated (σ g : ℝ → ℝ) (x : ℝ)
    (hσ : DifferentiableAt ℝ σ x) (hg : DifferentiableAt ℝ g x)
    (h_weyl : deriv g x = 2 * deriv σ x * g x) :
    deriv (fun y => gaugeTransform (g y) (σ y)) x = 0 := by
  rw [gaugeTransform_deriv σ g x hσ hg, h_weyl]
  unfold gaugeTransform
  ring

/-- Global gauge covariance: `SatisfiesNonMetricity α g` is carried by the
    gauge transform to the transformed pair `(α - dσ, e^{-2σ} g)`. -/
theorem gauge_covariance (α σ g : ℝ → ℝ)
    (hσ : Differentiable ℝ σ) (hg : Differentiable ℝ g)
    (h_weyl : SatisfiesNonMetricity α g) :
    SatisfiesNonMetricity (transformedAlpha α σ)
      (fun y => gaugeTransform (g y) (σ y)) := by
  rw [satisfiesNonMetricity_iff] at h_weyl ⊢
  intro x
  exact gauge_transforms_alpha α σ g x (hσ x) (hg x) (h_weyl x)

/-- **Gauge recovery of metric compatibility.**  If `g` satisfies the Weyl
    non-metricity equation with exact form `α = dσ`, the transformed metric
    `ĝ = e^{-2σ} g` satisfies it with `α = 0`, i.e. `ĝ` is metric-compatible
    and the connection is Levi-Civita (§3). -/
theorem gauge_recovers_metric_compatibility (σ g : ℝ → ℝ)
    (hσ : Differentiable ℝ σ) (hg : Differentiable ℝ g)
    (h_weyl : SatisfiesNonMetricity (deriv σ) g) :
    SatisfiesNonMetricity (fun _ => 0)
      (fun y => gaugeTransform (g y) (σ y)) := by
  have h := gauge_covariance (deriv σ) σ g hσ hg h_weyl
  rwa [transformedAlpha_exact] at h

/-- The hypotheses above are genuinely dischargeable: for every differentiable
    gauge potential `σ`, the metric `g = e^{2σ}` solves the non-metricity
    equation with the exact Weyl form `α = dσ`. -/
theorem exp_scale_satisfies_nonMetricity (σ : ℝ → ℝ) (hσ : Differentiable ℝ σ) :
    SatisfiesNonMetricity (deriv σ) (fun x => exp (2 * σ x)) := by
  rw [satisfiesNonMetricity_iff]
  intro x
  have h : HasDerivAt (fun y => exp (2 * σ y))
      (exp (2 * σ x) * (2 * deriv σ x)) x :=
    ((hσ x).hasDerivAt.const_mul (2 : ℝ)).exp
  rw [h.deriv]
  show exp (2 * σ x) * (2 * deriv σ x) = 2 * deriv σ x * exp (2 * σ x)
  ring

/-- End-to-end check: for `g = e^{2σ}` with exact `α = dσ`, the gauge
    transform produces a metric-compatible metric (indeed `ĝ = 1`). -/
example (σ : ℝ → ℝ) (hσ : Differentiable ℝ σ) :
    SatisfiesNonMetricity (fun _ => 0)
      (fun y => gaugeTransform (exp (2 * σ y)) (σ y)) :=
  gauge_recovers_metric_compatibility σ (fun x => exp (2 * σ x)) hσ
    (fun x => ((hσ x).const_mul (2 : ℝ)).exp)
    (exp_scale_satisfies_nonMetricity σ hσ)

/-! ## 5. Weyl Curvature Modification -/

def weylCurvatureCorrection (R_std α : ℝ) : ℝ :=
  R_std + 2 * α ^ 2

theorem curvature_standard_when_flat (R_std : ℝ) :
    weylCurvatureCorrection R_std 0 = R_std := by
  unfold weylCurvatureCorrection; ring

/-! ## 6. Scale Field Properties -/

def scaleField (σ : ℝ) : ℝ := exp σ

def alphaFromScale (σ : ℝ) : ℝ := σ

theorem scale_field_positive (σ : ℝ) : 0 < scaleField σ := by
  unfold scaleField; exact exp_pos σ

theorem scale_composition (σ₁ σ₂ : ℝ) :
    scaleField σ₁ * scaleField σ₂ = scaleField (σ₁ + σ₂) := by
  unfold scaleField; rw [← exp_add]

theorem alpha_additive (σ₁ σ₂ : ℝ) :
    alphaFromScale (σ₁ + σ₂) = alphaFromScale σ₁ + alphaFromScale σ₂ := by
  unfold alphaFromScale
  rfl

/-! ## 7. Weyl Rescaling of Tensor Weight -/

def weylRescale (T σ : ℝ) (w : ℤ) : ℝ := exp (↑w * σ) * T

theorem rescale_composition (T σ₁ σ₂ : ℝ) (w : ℤ) :
    weylRescale (weylRescale T σ₁ w) σ₂ w = weylRescale T (σ₁ + σ₂) w := by
  unfold weylRescale
  rw [show (↑w * (σ₁ + σ₂) : ℝ) = ↑w * σ₁ + ↑w * σ₂ from by ring, exp_add]
  ring

theorem rescale_identity (T : ℝ) (w : ℤ) :
    weylRescale T 0 w = T := by
  unfold weylRescale; simp

end RLA.WeylGeometry
